repos:
  repo: local
  hooks:
    id: pylint
    name: pylint
    entry: pylint
    language: system
    types: [python]
    args:
      [
        "-rn", # pm;y display messages
        "-sn", # don't display the score
        "--rcfile=.pylintrc", # linto to config file
        "--load-plugins=pylint.extensions.docparams" # load an extension
      ]